path_trace = {
    ('NTR', 'VDC'): ['NTR', 'VDC'],
    ('NTR', 'RBS'): ['NTR', 'VDC', 'i2', 'i25', 'i26', 'RBS'],
    ('NTR', 'VS'): ['NTR', 'VDC', 'i2', 'i25', 'i26', 'VS'],
    ('NTR', 'TC'): ['NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('NTR', 'IS'): ['NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('NTR', 'GSL'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('NTR', 'OA'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA'],
    ('NTR', 'CG'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('NTR', 'SS'): ['NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('NTR', 'GSB'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB'],
    ('NTR', 'KRC'): ['NTR', 'VDC', 'i2', 'KRC'],
    ('NTR', 'CP'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP'],
    ('NTR', 'CS'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS'],
    ('NTR', 'GTC'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'GTC'],
    ('NTR', 'CB'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB'],
    ('NTR', 'GP'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('NTR', 'DB'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('NTR', 'GB'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('NTR', 'GH'): ['NTR', 'BG', 'i12', 'i11', 'GH'],
    ('NTR', 'VB'): ['NTR', 'BG', 'i12', 'VB'],
    ('NTR', 'VBA'): ['NTR', 'BG', 'i12', 'VB', 'VBA'],
    ('NTR', 'CVB'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('NTR', 'ICT'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('NTR', 'AB'): ['NTR', 'BG', 'i12', 'i11', 'AB'],
    ('NTR', 'PB'): ['NTR', 'BG', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB'],
    ('NTR', 'IEB'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('NTR', 'DDS'): ['NTR', 'BG', 'i13', 'DDS'],
    ('NTR', 'CRL'): ['NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('NTR', 'MTP'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'MTP'],
    ('NTR', 'BG'): ['NTR', 'BG'],
    ('NTR', 'FG'): ['NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('VDC', 'NTR'): ['VDC', 'NTR'],
    ('VDC', 'RBS'): ['VDC', 'i2', 'i25', 'i26', 'RBS'],
    ('VDC', 'VS'): ['VDC', 'i2', 'i25', 'i26', 'VS'],
    ('VDC', 'TC'): ['VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('VDC', 'IS'): ['VDC', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('VDC', 'GSL'): ['VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('VDC', 'OA'): ['VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA'],
    ('VDC', 'CG'): ['VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('VDC', 'SS'): ['VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('VDC', 'GSB'): ['VDC', 'i2', 'KRC', 'i3', 'GSB'],
    ('VDC', 'KRC'): ['VDC', 'i2', 'KRC'],
    ('VDC', 'CP'): ['VDC', 'i2', 'KRC', 'i3', 'CP'],
    ('VDC', 'CS'): ['VDC', 'i2', 'KRC', 'i3', 'CP', 'CS'],
    ('VDC', 'GTC'): ['VDC', 'i2', 'KRC', 'i3', 'i21', 'GTC'],
    ('VDC', 'CB'): ['VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB'],
    ('VDC', 'GP'): ['VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('VDC', 'DB'): ['VDC', 'i2', 'KRC', 'i3', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('VDC', 'GB'): ['VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('VDC', 'GH'): ['VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('VDC', 'VB'): ['VDC', 'NTR', 'BG', 'i12', 'VB'],
    ('VDC', 'VBA'): ['VDC', 'NTR', 'BG', 'i12', 'VB', 'VBA'],
    ('VDC', 'CVB'): ['VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('VDC', 'ICT'): ['VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('VDC', 'AB'): ['VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('VDC', 'PB'): ['VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB'],
    ('VDC', 'IEB'): ['VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('VDC', 'DDS'): ['VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('VDC', 'CRL'): ['VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('VDC', 'MTP'): ['VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'MTP'],
    ('VDC', 'BG'): ['VDC', 'NTR', 'BG'],
    ('VDC', 'FG'): ['VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('RBS', 'NTR'): ['RBS', 'i26', 'i25', 'i2', 'VDC', 'NTR'],
    ('RBS', 'VDC'): ['RBS', 'i26', 'i25', 'i2', 'VDC'],
    ('RBS', 'VS'): ['RBS', 'i26', 'VS'],
    ('RBS', 'TC'): ['RBS', 'i26', 'VS', 'IS', 'TC'],
    ('RBS', 'IS'): ['RBS', 'i26', 'VS', 'IS'],
    ('RBS', 'GSL'): ['RBS', 'i26', 'VS', 'IS', 'GSL'],
    ('RBS', 'OA'): ['RBS', 'i26', 'VS', 'IS', 'GSL', 'OA'],
    ('RBS', 'CG'): ['RBS', 'i26', 'VS', 'IS', 'TC', 'i27', 'CG'],
    ('RBS', 'SS'): ['RBS', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('RBS', 'GSB'): ['RBS', 'i26', 'VS', 'IS', 'GSL', 'OA', 'i24', 'GSB'],
    ('RBS', 'KRC'): ['RBS', 'i26', 'i25', 'i2', 'KRC'],
    ('RBS', 'CP'): ['RBS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'CP'],
    ('RBS', 'CS'): ['RBS', 'i26', 'VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'CS'],
    ('RBS', 'GTC'): ['RBS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'GTC'],
    ('RBS', 'CB'): ['RBS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB'],
    ('RBS', 'GP'): ['RBS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('RBS', 'DB'): ['RBS', 'i26', 'VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('RBS', 'GB'): ['RBS', 'i26', 'VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'FG', 'GB'],
    ('RBS', 'GH'): ['RBS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('RBS', 'VB'): ['RBS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('RBS', 'VBA'): ['RBS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA'],
    ('RBS', 'CVB'): ['RBS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('RBS', 'ICT'): ['RBS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('RBS', 'AB'): ['RBS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('RBS', 'PB'): ['RBS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('RBS', 'IEB'): ['RBS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('RBS', 'DDS'): ['RBS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('RBS', 'CRL'): ['RBS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('RBS', 'MTP'): ['RBS', 'i26', 'VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'MTP'],
    ('RBS', 'BG'): ['RBS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG'],
    ('RBS', 'FG'): ['RBS', 'i26', 'VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'FG'],
    ('VS', 'NTR'): ['VS', 'i26', 'i25', 'i2', 'VDC', 'NTR'],
    ('VS', 'VDC'): ['VS', 'i26', 'i25', 'i2', 'VDC'],
    ('VS', 'RBS'): ['VS', 'i26', 'RBS'],
    ('VS', 'TC'): ['VS', 'IS', 'TC'],
    ('VS', 'IS'): ['VS', 'IS'],
    ('VS', 'GSL'): ['VS', 'IS', 'GSL'],
    ('VS', 'OA'): ['VS', 'IS', 'GSL', 'OA'],
    ('VS', 'CG'): ['VS', 'IS', 'TC', 'i27', 'CG'],
    ('VS', 'SS'): ['VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('VS', 'GSB'): ['VS', 'IS', 'GSL', 'OA', 'i24', 'GSB'],
    ('VS', 'KRC'): ['VS', 'i26', 'i25', 'i2', 'KRC'],
    ('VS', 'CP'): ['VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'CS', 'CP'],
    ('VS', 'CS'): ['VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'CS'],
    ('VS', 'GTC'): ['VS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'GTC'],
    ('VS', 'CB'): ['VS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB'],
    ('VS', 'GP'): ['VS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('VS', 'DB'): ['VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('VS', 'GB'): ['VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'FG', 'GB'],
    ('VS', 'GH'): ['VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('VS', 'VB'): ['VS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('VS', 'VBA'): ['VS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA'],
    ('VS', 'CVB'): ['VS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('VS', 'ICT'): ['VS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('VS', 'AB'): ['VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('VS', 'PB'): ['VS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('VS', 'IEB'): ['VS', 'i26', 'i25', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('VS', 'DDS'): ['VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('VS', 'CRL'): ['VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('VS', 'MTP'): ['VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'MTP'],
    ('VS', 'BG'): ['VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG'],
    ('VS', 'FG'): ['VS', 'IS', 'TC', 'i27', 'CG', 'i4', 'FG'],
    ('TC', 'NTR'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR'],
    ('TC', 'VDC'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC'],
    ('TC', 'RBS'): ['TC', 'IS', 'VS', 'i26', 'RBS'],
    ('TC', 'VS'): ['TC', 'IS', 'VS'],
    ('TC', 'IS'): ['TC', 'IS'],
    ('TC', 'GSL'): ['TC', 'IS', 'GSL'],
    ('TC', 'OA'): ['TC', 'IS', 'GSL', 'OA'],
    ('TC', 'CG'): ['TC', 'i27', 'CG'],
    ('TC', 'SS'): ['TC', 'i27', 'i28', 'SS'],
    ('TC', 'GSB'): ['TC', 'IS', 'GSL', 'OA', 'i24', 'GSB'],
    ('TC', 'KRC'): ['TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC'],
    ('TC', 'CP'): ['TC', 'i27', 'CG', 'i4', 'CS', 'CP'],
    ('TC', 'CS'): ['TC', 'i27', 'CG', 'i4', 'CS'],
    ('TC', 'GTC'): ['TC', 'i27', 'CG', 'i4', 'MTP', 'i20', 'GTC'],
    ('TC', 'CB'): ['TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB'],
    ('TC', 'GP'): ['TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('TC', 'DB'): ['TC', 'i27', 'CG', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('TC', 'GB'): ['TC', 'i27', 'CG', 'i4', 'FG', 'GB'],
    ('TC', 'GH'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('TC', 'VB'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('TC', 'VBA'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA'],
    ('TC', 'CVB'): ['TC', 'i27', 'CG', 'i4', 'MTP', 'i20', 'i19', 'i18', 'CVB'],
    ('TC', 'ICT'): ['TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('TC', 'AB'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('TC', 'PB'): ['TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('TC', 'IEB'): ['TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('TC', 'DDS'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('TC', 'CRL'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('TC', 'MTP'): ['TC', 'i27', 'CG', 'i4', 'MTP'],
    ('TC', 'BG'): ['TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG'],
    ('TC', 'FG'): ['TC', 'i27', 'CG', 'i4', 'FG'],
    ('IS', 'NTR'): ['IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR'],
    ('IS', 'VDC'): ['IS', 'VS', 'i26', 'i25', 'i2', 'VDC'],
    ('IS', 'RBS'): ['IS', 'VS', 'i26', 'RBS'],
    ('IS', 'VS'): ['IS', 'VS'],
    ('IS', 'TC'): ['IS', 'TC'],
    ('IS', 'GSL'): ['IS', 'GSL'],
    ('IS', 'OA'): ['IS', 'GSL', 'OA'],
    ('IS', 'CG'): ['IS', 'TC', 'i27', 'CG'],
    ('IS', 'SS'): ['IS', 'TC', 'i27', 'i28', 'SS'],
    ('IS', 'GSB'): ['IS', 'GSL', 'OA', 'i24', 'GSB'],
    ('IS', 'KRC'): ['IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC'],
    ('IS', 'CP'): ['IS', 'TC', 'i27', 'CG', 'i4', 'CS', 'CP'],
    ('IS', 'CS'): ['IS', 'TC', 'i27', 'CG', 'i4', 'CS'],
    ('IS', 'GTC'): ['IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'GTC'],
    ('IS', 'CB'): ['IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB'],
    ('IS', 'GP'): ['IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('IS', 'DB'): ['IS', 'TC', 'i27', 'CG', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('IS', 'GB'): ['IS', 'TC', 'i27', 'CG', 'i4', 'FG', 'GB'],
    ('IS', 'GH'): ['IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('IS', 'VB'): ['IS', 'VS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('IS', 'VBA'): ['IS', 'VS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA'],
    ('IS', 'CVB'): ['IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('IS', 'ICT'): ['IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('IS', 'AB'): ['IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('IS', 'PB'): ['IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('IS', 'IEB'): ['IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('IS', 'DDS'): ['IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('IS', 'CRL'): ['IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('IS', 'MTP'): ['IS', 'TC', 'i27', 'CG', 'i4', 'MTP'],
    ('IS', 'BG'): ['IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG'],
    ('IS', 'FG'): ['IS', 'TC', 'i27', 'CG', 'i4', 'FG'],
    ('GSL', 'NTR'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('GSL', 'VDC'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC'],
    ('GSL', 'RBS'): ['GSL', 'IS', 'VS', 'i26', 'RBS'],
    ('GSL', 'VS'): ['GSL', 'IS', 'VS'],
    ('GSL', 'TC'): ['GSL', 'IS', 'TC'],
    ('GSL', 'IS'): ['GSL', 'IS'],
    ('GSL', 'OA'): ['GSL', 'OA'],
    ('GSL', 'CG'): ['GSL', 'IS', 'TC', 'i27', 'CG'],
    ('GSL', 'SS'): ['GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('GSL', 'GSB'): ['GSL', 'OA', 'i24', 'GSB'],
    ('GSL', 'KRC'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC'],
    ('GSL', 'CP'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'CP'],
    ('GSL', 'CS'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'CP', 'CS'],
    ('GSL', 'GTC'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'GTC'],
    ('GSL', 'CB'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB'],
    ('GSL', 'GP'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('GSL', 'DB'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('GSL', 'GB'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('GSL', 'GH'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('GSL', 'VB'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('GSL', 'VBA'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('GSL', 'CVB'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('GSL', 'ICT'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('GSL', 'AB'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('GSL', 'PB'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('GSL', 'IEB'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('GSL', 'DDS'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('GSL', 'CRL'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('GSL', 'MTP'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'CP', 'CS', 'i4', 'MTP'],
    ('GSL', 'BG'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('GSL', 'FG'): ['GSL', 'OA', 'i24', 'GSB', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('OA', 'NTR'): ['OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('OA', 'VDC'): ['OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC'],
    ('OA', 'RBS'): ['OA', 'GSL', 'IS', 'VS', 'i26', 'RBS'],
    ('OA', 'VS'): ['OA', 'GSL', 'IS', 'VS'],
    ('OA', 'TC'): ['OA', 'GSL', 'IS', 'TC'],
    ('OA', 'IS'): ['OA', 'GSL', 'IS'],
    ('OA', 'GSL'): ['OA', 'GSL'],
    ('OA', 'CG'): ['OA', 'GSL', 'IS', 'TC', 'i27', 'CG'],
    ('OA', 'SS'): ['OA', 'GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('OA', 'GSB'): ['OA', 'i24', 'GSB'],
    ('OA', 'KRC'): ['OA', 'i24', 'GSB', 'i3', 'KRC'],
    ('OA', 'CP'): ['OA', 'i24', 'GSB', 'i3', 'CP'],
    ('OA', 'CS'): ['OA', 'i24', 'GSB', 'i3', 'CP', 'CS'],
    ('OA', 'GTC'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'GTC'],
    ('OA', 'CB'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB'],
    ('OA', 'GP'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('OA', 'DB'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('OA', 'GB'): ['OA', 'i24', 'GSB', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('OA', 'GH'): ['OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('OA', 'VB'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('OA', 'VBA'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('OA', 'CVB'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('OA', 'ICT'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('OA', 'AB'): ['OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('OA', 'PB'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('OA', 'IEB'): ['OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('OA', 'DDS'): ['OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('OA', 'CRL'): ['OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('OA', 'MTP'): ['OA', 'i24', 'GSB', 'i3', 'CP', 'CS', 'i4', 'MTP'],
    ('OA', 'BG'): ['OA', 'i24', 'GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('OA', 'FG'): ['OA', 'i24', 'GSB', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('CG', 'NTR'): ['CG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('CG', 'VDC'): ['CG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC'],
    ('CG', 'RBS'): ['CG', 'i27', 'TC', 'IS', 'VS', 'i26', 'RBS'],
    ('CG', 'VS'): ['CG', 'i27', 'TC', 'IS', 'VS'],
    ('CG', 'TC'): ['CG', 'i27', 'TC'],
    ('CG', 'IS'): ['CG', 'i27', 'TC', 'IS'],
    ('CG', 'GSL'): ['CG', 'i27', 'TC', 'IS', 'GSL'],
    ('CG', 'OA'): ['CG', 'i27', 'TC', 'IS', 'GSL', 'OA'],
    ('CG', 'SS'): ['CG', 'i27', 'i28', 'SS'],
    ('CG', 'GSB'): ['CG', 'i27', 'TC', 'IS', 'GSL', 'OA', 'i24', 'GSB'],
    ('CG', 'KRC'): ['CG', 'i4', 'CS', 'CP', 'i3', 'KRC'],
    ('CG', 'CP'): ['CG', 'i4', 'CS', 'CP'],
    ('CG', 'CS'): ['CG', 'i4', 'CS'],
    ('CG', 'GTC'): ['CG', 'i4', 'MTP', 'i20', 'GTC'],
    ('CG', 'CB'): ['CG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'CB'],
    ('CG', 'GP'): ['CG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('CG', 'DB'): ['CG', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('CG', 'GB'): ['CG', 'i4', 'FG', 'GB'],
    ('CG', 'GH'): ['CG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('CG', 'VB'): ['CG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('CG', 'VBA'): ['CG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('CG', 'CVB'): ['CG', 'i4', 'MTP', 'i20', 'i19', 'i18', 'CVB'],
    ('CG', 'ICT'): ['CG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('CG', 'AB'): ['CG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('CG', 'PB'): ['CG', 'i4', 'MTP', 'i20', 'i19', 'i18', 'i7', 'i9', 'IEB', 'PB'],
    ('CG', 'IEB'): ['CG', 'i4', 'MTP', 'i20', 'i19', 'i18', 'i7', 'i9', 'IEB'],
    ('CG', 'DDS'): ['CG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('CG', 'CRL'): ['CG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('CG', 'MTP'): ['CG', 'i4', 'MTP'],
    ('CG', 'BG'): ['CG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('CG', 'FG'): ['CG', 'i4', 'FG'],
    ('SS', 'NTR'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR'],
    ('SS', 'VDC'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC'],
    ('SS', 'RBS'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'RBS'],
    ('SS', 'VS'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS'],
    ('SS', 'TC'): ['SS', 'i28', 'i27', 'TC'],
    ('SS', 'IS'): ['SS', 'i28', 'i27', 'TC', 'IS'],
    ('SS', 'GSL'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL'],
    ('SS', 'OA'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL', 'OA'],
    ('SS', 'CG'): ['SS', 'i28', 'i27', 'CG'],
    ('SS', 'GSB'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL', 'OA', 'i24', 'GSB'],
    ('SS', 'KRC'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'KRC'],
    ('SS', 'CP'): ['SS', 'i28', 'i27', 'CG', 'i4', 'CS', 'CP'],
    ('SS', 'CS'): ['SS', 'i28', 'i27', 'CG', 'i4', 'CS'],
    ('SS', 'GTC'): ['SS', 'i28', 'i27', 'CG', 'i4', 'MTP', 'i20', 'GTC'],
    ('SS', 'CB'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB'],
    ('SS', 'GP'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('SS', 'DB'): ['SS', 'i28', 'i27', 'CG', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('SS', 'GB'): ['SS', 'i31', 'i32', 'FG', 'GB'],
    ('SS', 'GH'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('SS', 'VB'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('SS', 'VBA'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'i23', 'i15', 'i14', 'VBA'],
    ('SS', 'CVB'): ['SS', 'i28', 'i27', 'CG', 'i4', 'MTP', 'i20', 'i19', 'i18', 'CVB'],
    ('SS', 'ICT'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('SS', 'AB'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('SS', 'PB'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('SS', 'IEB'): ['SS', 'i28', 'i27', 'TC', 'IS', 'GSL', 'OA', 'i24', 'GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('SS', 'DDS'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('SS', 'CRL'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('SS', 'MTP'): ['SS', 'i28', 'i27', 'CG', 'i4', 'MTP'],
    ('SS', 'BG'): ['SS', 'i28', 'i27', 'TC', 'IS', 'VS', 'i26', 'i25', 'i2', 'VDC', 'NTR', 'BG'],
    ('SS', 'FG'): ['SS', 'i31', 'i32', 'FG'],
    ('GSB', 'NTR'): ['GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('GSB', 'VDC'): ['GSB', 'i3', 'KRC', 'i2', 'VDC'],
    ('GSB', 'RBS'): ['GSB', 'i24', 'OA', 'GSL', 'IS', 'VS', 'i26', 'RBS'],
    ('GSB', 'VS'): ['GSB', 'i24', 'OA', 'GSL', 'IS', 'VS'],
    ('GSB', 'TC'): ['GSB', 'i24', 'OA', 'GSL', 'IS', 'TC'],
    ('GSB', 'IS'): ['GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('GSB', 'GSL'): ['GSB', 'i24', 'OA', 'GSL'],
    ('GSB', 'OA'): ['GSB', 'i24', 'OA'],
    ('GSB', 'CG'): ['GSB', 'i24', 'OA', 'GSL', 'IS', 'TC', 'i27', 'CG'],
    ('GSB', 'SS'): ['GSB', 'i24', 'OA', 'GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('GSB', 'KRC'): ['GSB', 'i3', 'KRC'],
    ('GSB', 'CP'): ['GSB', 'i3', 'CP'],
    ('GSB', 'CS'): ['GSB', 'i3', 'CP', 'CS'],
    ('GSB', 'GTC'): ['GSB', 'i3', 'i21', 'GTC'],
    ('GSB', 'CB'): ['GSB', 'i3', 'i21', 'i22', 'CB'],
    ('GSB', 'GP'): ['GSB', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('GSB', 'DB'): ['GSB', 'i3', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('GSB', 'GB'): ['GSB', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('GSB', 'GH'): ['GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('GSB', 'VB'): ['GSB', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('GSB', 'VBA'): ['GSB', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('GSB', 'CVB'): ['GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('GSB', 'ICT'): ['GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('GSB', 'AB'): ['GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('GSB', 'PB'): ['GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('GSB', 'IEB'): ['GSB', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('GSB', 'DDS'): ['GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('GSB', 'CRL'): ['GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('GSB', 'MTP'): ['GSB', 'i3', 'CP', 'CS', 'i4', 'MTP'],
    ('GSB', 'BG'): ['GSB', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('GSB', 'FG'): ['GSB', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('KRC', 'NTR'): ['KRC', 'i2', 'VDC', 'NTR'],
    ('KRC', 'VDC'): ['KRC', 'i2', 'VDC'],
    ('KRC', 'RBS'): ['KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('KRC', 'VS'): ['KRC', 'i2', 'i25', 'i26', 'VS'],
    ('KRC', 'TC'): ['KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC'],
    ('KRC', 'IS'): ['KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('KRC', 'GSL'): ['KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('KRC', 'OA'): ['KRC', 'i3', 'GSB', 'i24', 'OA'],
    ('KRC', 'CG'): ['KRC', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('KRC', 'SS'): ['KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('KRC', 'GSB'): ['KRC', 'i3', 'GSB'],
    ('KRC', 'CP'): ['KRC', 'i3', 'CP'],
    ('KRC', 'CS'): ['KRC', 'i3', 'CP', 'CS'],
    ('KRC', 'GTC'): ['KRC', 'i3', 'i21', 'GTC'],
    ('KRC', 'CB'): ['KRC', 'i3', 'i21', 'i22', 'CB'],
    ('KRC', 'GP'): ['KRC', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('KRC', 'DB'): ['KRC', 'i3', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('KRC', 'GB'): ['KRC', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('KRC', 'GH'): ['KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('KRC', 'VB'): ['KRC', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('KRC', 'VBA'): ['KRC', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('KRC', 'CVB'): ['KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('KRC', 'ICT'): ['KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('KRC', 'AB'): ['KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('KRC', 'PB'): ['KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('KRC', 'IEB'): ['KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('KRC', 'DDS'): ['KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('KRC', 'CRL'): ['KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('KRC', 'MTP'): ['KRC', 'i3', 'CP', 'CS', 'i4', 'MTP'],
    ('KRC', 'BG'): ['KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('KRC', 'FG'): ['KRC', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('CP', 'NTR'): ['CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('CP', 'VDC'): ['CP', 'i3', 'KRC', 'i2', 'VDC'],
    ('CP', 'RBS'): ['CP', 'i3', 'KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('CP', 'VS'): ['CP', 'CS', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS'],
    ('CP', 'TC'): ['CP', 'CS', 'i4', 'CG', 'i27', 'TC'],
    ('CP', 'IS'): ['CP', 'CS', 'i4', 'CG', 'i27', 'TC', 'IS'],
    ('CP', 'GSL'): ['CP', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('CP', 'OA'): ['CP', 'i3', 'GSB', 'i24', 'OA'],
    ('CP', 'CG'): ['CP', 'CS', 'i4', 'CG'],
    ('CP', 'SS'): ['CP', 'CS', 'i4', 'CG', 'i27', 'i28', 'SS'],
    ('CP', 'GSB'): ['CP', 'i3', 'GSB'],
    ('CP', 'KRC'): ['CP', 'i3', 'KRC'],
    ('CP', 'CS'): ['CP', 'CS'],
    ('CP', 'GTC'): ['CP', 'CS', 'i4', 'MTP', 'i20', 'GTC'],
    ('CP', 'CB'): ['CP', 'i3', 'i21', 'i22', 'CB'],
    ('CP', 'GP'): ['CP', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('CP', 'DB'): ['CP', 'CS', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('CP', 'GB'): ['CP', 'CS', 'i4', 'FG', 'GB'],
    ('CP', 'GH'): ['CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('CP', 'VB'): ['CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('CP', 'VBA'): ['CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('CP', 'CVB'): ['CP', 'CS', 'i4', 'MTP', 'i20', 'i19', 'i18', 'CVB'],
    ('CP', 'ICT'): ['CP', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('CP', 'AB'): ['CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('CP', 'PB'): ['CP', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('CP', 'IEB'): ['CP', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('CP', 'DDS'): ['CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('CP', 'CRL'): ['CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('CP', 'MTP'): ['CP', 'CS', 'i4', 'MTP'],
    ('CP', 'BG'): ['CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('CP', 'FG'): ['CP', 'CS', 'i4', 'FG'],
    ('CS', 'NTR'): ['CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('CS', 'VDC'): ['CS', 'CP', 'i3', 'KRC', 'i2', 'VDC'],
    ('CS', 'RBS'): ['CS', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS', 'i26', 'RBS'],
    ('CS', 'VS'): ['CS', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS'],
    ('CS', 'TC'): ['CS', 'i4', 'CG', 'i27', 'TC'],
    ('CS', 'IS'): ['CS', 'i4', 'CG', 'i27', 'TC', 'IS'],
    ('CS', 'GSL'): ['CS', 'CP', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('CS', 'OA'): ['CS', 'CP', 'i3', 'GSB', 'i24', 'OA'],
    ('CS', 'CG'): ['CS', 'i4', 'CG'],
    ('CS', 'SS'): ['CS', 'i4', 'CG', 'i27', 'i28', 'SS'],
    ('CS', 'GSB'): ['CS', 'CP', 'i3', 'GSB'],
    ('CS', 'KRC'): ['CS', 'CP', 'i3', 'KRC'],
    ('CS', 'CP'): ['CS', 'CP'],
    ('CS', 'GTC'): ['CS', 'i4', 'MTP', 'i20', 'GTC'],
    ('CS', 'CB'): ['CS', 'CP', 'i3', 'i21', 'i22', 'CB'],
    ('CS', 'GP'): ['CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('CS', 'DB'): ['CS', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('CS', 'GB'): ['CS', 'i4', 'FG', 'GB'],
    ('CS', 'GH'): ['CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('CS', 'VB'): ['CS', 'CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('CS', 'VBA'): ['CS', 'CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('CS', 'CVB'): ['CS', 'i4', 'MTP', 'i20', 'i19', 'i18', 'CVB'],
    ('CS', 'ICT'): ['CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('CS', 'AB'): ['CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('CS', 'PB'): ['CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('CS', 'IEB'): ['CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('CS', 'DDS'): ['CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('CS', 'CRL'): ['CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('CS', 'MTP'): ['CS', 'i4', 'MTP'],
    ('CS', 'BG'): ['CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('CS', 'FG'): ['CS', 'i4', 'FG'],
    ('GTC', 'NTR'): ['GTC', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('GTC', 'VDC'): ['GTC', 'i21', 'i3', 'KRC', 'i2', 'VDC'],
    ('GTC', 'RBS'): ['GTC', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('GTC', 'VS'): ['GTC', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'VS'],
    ('GTC', 'TC'): ['GTC', 'i20', 'MTP', 'i4', 'CG', 'i27', 'TC'],
    ('GTC', 'IS'): ['GTC', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('GTC', 'GSL'): ['GTC', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('GTC', 'OA'): ['GTC', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('GTC', 'CG'): ['GTC', 'i20', 'MTP', 'i4', 'CG'],
    ('GTC', 'SS'): ['GTC', 'i20', 'MTP', 'i4', 'CG', 'i27', 'i28', 'SS'],
    ('GTC', 'GSB'): ['GTC', 'i21', 'i3', 'GSB'],
    ('GTC', 'KRC'): ['GTC', 'i21', 'i3', 'KRC'],
    ('GTC', 'CP'): ['GTC', 'i20', 'MTP', 'i4', 'CS', 'CP'],
    ('GTC', 'CS'): ['GTC', 'i20', 'MTP', 'i4', 'CS'],
    ('GTC', 'CB'): ['GTC', 'i21', 'i22', 'CB'],
    ('GTC', 'GP'): ['GTC', 'i21', 'i22', 'CB', 'GP'],
    ('GTC', 'DB'): ['GTC', 'i20', 'i19', 'DB'],
    ('GTC', 'GB'): ['GTC', 'i20', 'MTP', 'i4', 'FG', 'GB'],
    ('GTC', 'GH'): ['GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'GH'],
    ('GTC', 'VB'): ['GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('GTC', 'VBA'): ['GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('GTC', 'CVB'): ['GTC', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('GTC', 'ICT'): ['GTC', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('GTC', 'AB'): ['GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB'],
    ('GTC', 'PB'): ['GTC', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('GTC', 'IEB'): ['GTC', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('GTC', 'DDS'): ['GTC', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('GTC', 'CRL'): ['GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB', 'CRL'],
    ('GTC', 'MTP'): ['GTC', 'i20', 'MTP'],
    ('GTC', 'BG'): ['GTC', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('GTC', 'FG'): ['GTC', 'i20', 'MTP', 'i4', 'FG'],
    ('CB', 'NTR'): ['CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('CB', 'VDC'): ['CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC'],
    ('CB', 'RBS'): ['CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('CB', 'VS'): ['CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'VS'],
    ('CB', 'TC'): ['CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC'],
    ('CB', 'IS'): ['CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('CB', 'GSL'): ['CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('CB', 'OA'): ['CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('CB', 'CG'): ['CB', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('CB', 'SS'): ['CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('CB', 'GSB'): ['CB', 'i22', 'i21', 'i3', 'GSB'],
    ('CB', 'KRC'): ['CB', 'i22', 'i21', 'i3', 'KRC'],
    ('CB', 'CP'): ['CB', 'i22', 'i21', 'i3', 'CP'],
    ('CB', 'CS'): ['CB', 'i22', 'i21', 'i3', 'CP', 'CS'],
    ('CB', 'GTC'): ['CB', 'i22', 'i21', 'GTC'],
    ('CB', 'GP'): ['CB', 'GP'],
    ('CB', 'DB'): ['CB', 'i22', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('CB', 'GB'): ['CB', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('CB', 'GH'): ['CB', 'GP', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'GH'],
    ('CB', 'VB'): ['CB', 'GP', 'i16', 'i15', 'i14', 'VBA', 'VB'],
    ('CB', 'VBA'): ['CB', 'GP', 'i16', 'i15', 'i14', 'VBA'],
    ('CB', 'CVB'): ['CB', 'GP', 'i16', 'CVB'],
    ('CB', 'ICT'): ['CB', 'GP', 'i16', 'ICT'],
    ('CB', 'AB'): ['CB', 'GP', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB'],
    ('CB', 'PB'): ['CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('CB', 'IEB'): ['CB', 'GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('CB', 'DDS'): ['CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('CB', 'CRL'): ['CB', 'GP', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB', 'CRL'],
    ('CB', 'MTP'): ['CB', 'i22', 'i21', 'GTC', 'i20', 'MTP'],
    ('CB', 'BG'): ['CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('CB', 'FG'): ['CB', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('GP', 'NTR'): ['GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('GP', 'VDC'): ['GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC'],
    ('GP', 'RBS'): ['GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('GP', 'VS'): ['GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'VS'],
    ('GP', 'TC'): ['GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC'],
    ('GP', 'IS'): ['GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('GP', 'GSL'): ['GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('GP', 'OA'): ['GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('GP', 'CG'): ['GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('GP', 'SS'): ['GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('GP', 'GSB'): ['GP', 'CB', 'i22', 'i21', 'i3', 'GSB'],
    ('GP', 'KRC'): ['GP', 'CB', 'i22', 'i21', 'i3', 'KRC'],
    ('GP', 'CP'): ['GP', 'CB', 'i22', 'i21', 'i3', 'CP'],
    ('GP', 'CS'): ['GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS'],
    ('GP', 'GTC'): ['GP', 'CB', 'i22', 'i21', 'GTC'],
    ('GP', 'CB'): ['GP', 'CB'],
    ('GP', 'DB'): ['GP', 'CB', 'i22', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('GP', 'GB'): ['GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('GP', 'GH'): ['GP', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'GH'],
    ('GP', 'VB'): ['GP', 'i16', 'i15', 'i14', 'VBA', 'VB'],
    ('GP', 'VBA'): ['GP', 'i16', 'i15', 'i14', 'VBA'],
    ('GP', 'CVB'): ['GP', 'i16', 'CVB'],
    ('GP', 'ICT'): ['GP', 'i16', 'ICT'],
    ('GP', 'AB'): ['GP', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB'],
    ('GP', 'PB'): ['GP', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('GP', 'IEB'): ['GP', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('GP', 'DDS'): ['GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('GP', 'CRL'): ['GP', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB', 'CRL'],
    ('GP', 'MTP'): ['GP', 'CB', 'i22', 'i21', 'GTC', 'i20', 'MTP'],
    ('GP', 'BG'): ['GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('GP', 'FG'): ['GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('DB', 'NTR'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('DB', 'VDC'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC'],
    ('DB', 'RBS'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS', 'i26', 'RBS'],
    ('DB', 'VS'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS'],
    ('DB', 'TC'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CG', 'i27', 'TC'],
    ('DB', 'IS'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CG', 'i27', 'TC', 'IS'],
    ('DB', 'GSL'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('DB', 'OA'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP', 'i3', 'GSB', 'i24', 'OA'],
    ('DB', 'CG'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CG'],
    ('DB', 'SS'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CG', 'i27', 'i28', 'SS'],
    ('DB', 'GSB'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP', 'i3', 'GSB'],
    ('DB', 'KRC'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP', 'i3', 'KRC'],
    ('DB', 'CP'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP'],
    ('DB', 'CS'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS'],
    ('DB', 'GTC'): ['DB', 'i19', 'i20', 'GTC'],
    ('DB', 'CB'): ['DB', 'i19', 'i20', 'GTC', 'i21', 'i22', 'CB'],
    ('DB', 'GP'): ['DB', 'i19', 'i20', 'GTC', 'i21', 'i22', 'CB', 'GP'],
    ('DB', 'GB'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'FG', 'GB'],
    ('DB', 'GH'): ['DB', 'i19', 'i18', 'CVB', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'GH'],
    ('DB', 'VB'): ['DB', 'i19', 'i18', 'CVB', 'i16', 'i15', 'i14', 'VBA', 'VB'],
    ('DB', 'VBA'): ['DB', 'i19', 'i18', 'CVB', 'i16', 'i15', 'i14', 'VBA'],
    ('DB', 'CVB'): ['DB', 'i19', 'i18', 'CVB'],
    ('DB', 'ICT'): ['DB', 'i19', 'i18', 'CVB', 'i16', 'ICT'],
    ('DB', 'AB'): ['DB', 'i19', 'i18', 'CVB', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB'],
    ('DB', 'PB'): ['DB', 'i19', 'i18', 'i7', 'i9', 'IEB', 'PB'],
    ('DB', 'IEB'): ['DB', 'i19', 'i18', 'i7', 'i9', 'IEB'],
    ('DB', 'DDS'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('DB', 'CRL'): ['DB', 'i19', 'i18', 'i7', 'i9', 'IEB', 'PB', 'i10', 'CRL'],
    ('DB', 'MTP'): ['DB', 'i19', 'i20', 'MTP'],
    ('DB', 'BG'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('DB', 'FG'): ['DB', 'i19', 'i20', 'MTP', 'i4', 'FG'],
    ('GB', 'NTR'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('GB', 'VDC'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC'],
    ('GB', 'RBS'): ['GB', 'FG', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS', 'i26', 'RBS'],
    ('GB', 'VS'): ['GB', 'FG', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS'],
    ('GB', 'TC'): ['GB', 'FG', 'i4', 'CG', 'i27', 'TC'],
    ('GB', 'IS'): ['GB', 'FG', 'i4', 'CG', 'i27', 'TC', 'IS'],
    ('GB', 'GSL'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('GB', 'OA'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'GSB', 'i24', 'OA'],
    ('GB', 'CG'): ['GB', 'FG', 'i4', 'CG'],
    ('GB', 'SS'): ['GB', 'FG', 'i32', 'i31', 'SS'],
    ('GB', 'GSB'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'GSB'],
    ('GB', 'KRC'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'KRC'],
    ('GB', 'CP'): ['GB', 'FG', 'i4', 'CS', 'CP'],
    ('GB', 'CS'): ['GB', 'FG', 'i4', 'CS'],
    ('GB', 'GTC'): ['GB', 'FG', 'i4', 'MTP', 'i20', 'GTC'],
    ('GB', 'CB'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'CB'],
    ('GB', 'GP'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('GB', 'DB'): ['GB', 'FG', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('GB', 'GH'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('GB', 'VB'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('GB', 'VBA'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('GB', 'CVB'): ['GB', 'i6', 'i7', 'i18', 'CVB'],
    ('GB', 'ICT'): ['GB', 'i6', 'i7', 'i9', 'i8', 'ICT'],
    ('GB', 'AB'): ['GB', 'i6', 'i7', 'i9', 'IEB', 'PB', 'i10', 'CRL', 'AB'],
    ('GB', 'PB'): ['GB', 'i6', 'i7', 'i9', 'IEB', 'PB'],
    ('GB', 'IEB'): ['GB', 'i6', 'i7', 'i9', 'IEB'],
    ('GB', 'DDS'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('GB', 'CRL'): ['GB', 'i6', 'i7', 'i9', 'IEB', 'PB', 'i10', 'CRL'],
    ('GB', 'MTP'): ['GB', 'FG', 'i4', 'MTP'],
    ('GB', 'BG'): ['GB', 'FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('GB', 'FG'): ['GB', 'FG'],
    ('GH', 'NTR'): ['GH', 'i11', 'i12', 'BG', 'NTR'],
    ('GH', 'VDC'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC'],
    ('GH', 'RBS'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'RBS'],
    ('GH', 'VS'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS'],
    ('GH', 'TC'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('GH', 'IS'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('GH', 'GSL'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('GH', 'OA'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA'],
    ('GH', 'CG'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('GH', 'SS'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('GH', 'GSB'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB'],
    ('GH', 'KRC'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC'],
    ('GH', 'CP'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP'],
    ('GH', 'CS'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS'],
    ('GH', 'GTC'): ['GH', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC'],
    ('GH', 'CB'): ['GH', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'GP', 'CB'],
    ('GH', 'GP'): ['GH', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'GP'],
    ('GH', 'DB'): ['GH', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'CVB', 'i18', 'i19', 'DB'],
    ('GH', 'GB'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('GH', 'VB'): ['GH', 'i11', 'i12', 'VB'],
    ('GH', 'VBA'): ['GH', 'i11', 'i12', 'VB', 'VBA'],
    ('GH', 'CVB'): ['GH', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'CVB'],
    ('GH', 'ICT'): ['GH', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'ICT'],
    ('GH', 'AB'): ['GH', 'i11', 'AB'],
    ('GH', 'PB'): ['GH', 'i11', 'AB', 'CRL', 'i10', 'PB'],
    ('GH', 'IEB'): ['GH', 'i11', 'AB', 'CRL', 'i10', 'PB', 'IEB'],
    ('GH', 'DDS'): ['GH', 'i11', 'i12', 'BG', 'i13', 'DDS'],
    ('GH', 'CRL'): ['GH', 'i11', 'AB', 'CRL'],
    ('GH', 'MTP'): ['GH', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC', 'i20', 'MTP'],
    ('GH', 'BG'): ['GH', 'i11', 'i12', 'BG'],
    ('GH', 'FG'): ['GH', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('VB', 'NTR'): ['VB', 'i12', 'BG', 'NTR'],
    ('VB', 'VDC'): ['VB', 'i12', 'BG', 'NTR', 'VDC'],
    ('VB', 'RBS'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'RBS'],
    ('VB', 'VS'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'VS'],
    ('VB', 'TC'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('VB', 'IS'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('VB', 'GSL'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('VB', 'OA'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('VB', 'CG'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('VB', 'SS'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('VB', 'GSB'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'GSB'],
    ('VB', 'KRC'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'KRC'],
    ('VB', 'CP'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP'],
    ('VB', 'CS'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP', 'CS'],
    ('VB', 'GTC'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC'],
    ('VB', 'CB'): ['VB', 'VBA', 'i14', 'i15', 'i16', 'GP', 'CB'],
    ('VB', 'GP'): ['VB', 'VBA', 'i14', 'i15', 'i16', 'GP'],
    ('VB', 'DB'): ['VB', 'VBA', 'i14', 'i15', 'i16', 'CVB', 'i18', 'i19', 'DB'],
    ('VB', 'GB'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('VB', 'GH'): ['VB', 'i12', 'i11', 'GH'],
    ('VB', 'VBA'): ['VB', 'VBA'],
    ('VB', 'CVB'): ['VB', 'VBA', 'i14', 'i15', 'i16', 'CVB'],
    ('VB', 'ICT'): ['VB', 'VBA', 'i14', 'i15', 'i16', 'ICT'],
    ('VB', 'AB'): ['VB', 'i12', 'i11', 'AB'],
    ('VB', 'PB'): ['VB', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB'],
    ('VB', 'IEB'): ['VB', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB', 'IEB'],
    ('VB', 'DDS'): ['VB', 'i12', 'BG', 'i13', 'DDS'],
    ('VB', 'CRL'): ['VB', 'i12', 'i11', 'AB', 'CRL'],
    ('VB', 'MTP'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC', 'i20', 'MTP'],
    ('VB', 'BG'): ['VB', 'i12', 'BG'],
    ('VB', 'FG'): ['VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('VBA', 'NTR'): ['VBA', 'VB', 'i12', 'BG', 'NTR'],
    ('VBA', 'VDC'): ['VBA', 'VB', 'i12', 'BG', 'NTR', 'VDC'],
    ('VBA', 'RBS'): ['VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'RBS'],
    ('VBA', 'VS'): ['VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'VS'],
    ('VBA', 'TC'): ['VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('VBA', 'IS'): ['VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('VBA', 'GSL'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('VBA', 'OA'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('VBA', 'CG'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('VBA', 'SS'): ['VBA', 'i14', 'i15', 'i23', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('VBA', 'GSB'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'GSB'],
    ('VBA', 'KRC'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'KRC'],
    ('VBA', 'CP'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP'],
    ('VBA', 'CS'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP', 'CS'],
    ('VBA', 'GTC'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC'],
    ('VBA', 'CB'): ['VBA', 'i14', 'i15', 'i16', 'GP', 'CB'],
    ('VBA', 'GP'): ['VBA', 'i14', 'i15', 'i16', 'GP'],
    ('VBA', 'DB'): ['VBA', 'i14', 'i15', 'i16', 'CVB', 'i18', 'i19', 'DB'],
    ('VBA', 'GB'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('VBA', 'GH'): ['VBA', 'VB', 'i12', 'i11', 'GH'],
    ('VBA', 'VB'): ['VBA', 'VB'],
    ('VBA', 'CVB'): ['VBA', 'i14', 'i15', 'i16', 'CVB'],
    ('VBA', 'ICT'): ['VBA', 'i14', 'i15', 'i16', 'ICT'],
    ('VBA', 'AB'): ['VBA', 'VB', 'i12', 'i11', 'AB'],
    ('VBA', 'PB'): ['VBA', 'VB', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB'],
    ('VBA', 'IEB'): ['VBA', 'i14', 'i17', 'i8', 'i9', 'IEB'],
    ('VBA', 'DDS'): ['VBA', 'VB', 'i12', 'BG', 'i13', 'DDS'],
    ('VBA', 'CRL'): ['VBA', 'VB', 'i12', 'i11', 'AB', 'CRL'],
    ('VBA', 'MTP'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC', 'i20', 'MTP'],
    ('VBA', 'BG'): ['VBA', 'VB', 'i12', 'BG'],
    ('VBA', 'FG'): ['VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('CVB', 'NTR'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('CVB', 'VDC'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC'],
    ('CVB', 'RBS'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('CVB', 'VS'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'VS'],
    ('CVB', 'TC'): ['CVB', 'i18', 'i19', 'i20', 'MTP', 'i4', 'CG', 'i27', 'TC'],
    ('CVB', 'IS'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('CVB', 'GSL'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('CVB', 'OA'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('CVB', 'CG'): ['CVB', 'i18', 'i19', 'i20', 'MTP', 'i4', 'CG'],
    ('CVB', 'SS'): ['CVB', 'i18', 'i19', 'i20', 'MTP', 'i4', 'CG', 'i27', 'i28', 'SS'],
    ('CVB', 'GSB'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB'],
    ('CVB', 'KRC'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC'],
    ('CVB', 'CP'): ['CVB', 'i18', 'i19', 'i20', 'MTP', 'i4', 'CS', 'CP'],
    ('CVB', 'CS'): ['CVB', 'i18', 'i19', 'i20', 'MTP', 'i4', 'CS'],
    ('CVB', 'GTC'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'GTC'],
    ('CVB', 'CB'): ['CVB', 'i16', 'GP', 'CB'],
    ('CVB', 'GP'): ['CVB', 'i16', 'GP'],
    ('CVB', 'DB'): ['CVB', 'i18', 'i19', 'DB'],
    ('CVB', 'GB'): ['CVB', 'i18', 'i7', 'i6', 'GB'],
    ('CVB', 'GH'): ['CVB', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'GH'],
    ('CVB', 'VB'): ['CVB', 'i16', 'i15', 'i14', 'VBA', 'VB'],
    ('CVB', 'VBA'): ['CVB', 'i16', 'i15', 'i14', 'VBA'],
    ('CVB', 'ICT'): ['CVB', 'i16', 'ICT'],
    ('CVB', 'AB'): ['CVB', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB'],
    ('CVB', 'PB'): ['CVB', 'i16', 'ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('CVB', 'IEB'): ['CVB', 'i16', 'ICT', 'i8', 'i9', 'IEB'],
    ('CVB', 'DDS'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('CVB', 'CRL'): ['CVB', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB', 'CRL'],
    ('CVB', 'MTP'): ['CVB', 'i18', 'i19', 'i20', 'MTP'],
    ('CVB', 'BG'): ['CVB', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('CVB', 'FG'): ['CVB', 'i18', 'i19', 'i20', 'MTP', 'i4', 'FG'],
    ('ICT', 'NTR'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('ICT', 'VDC'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC'],
    ('ICT', 'RBS'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('ICT', 'VS'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'VS'],
    ('ICT', 'TC'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC'],
    ('ICT', 'IS'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('ICT', 'GSL'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('ICT', 'OA'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('ICT', 'CG'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('ICT', 'SS'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('ICT', 'GSB'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB'],
    ('ICT', 'KRC'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC'],
    ('ICT', 'CP'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'CP'],
    ('ICT', 'CS'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS'],
    ('ICT', 'GTC'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'GTC'],
    ('ICT', 'CB'): ['ICT', 'i16', 'GP', 'CB'],
    ('ICT', 'GP'): ['ICT', 'i16', 'GP'],
    ('ICT', 'DB'): ['ICT', 'i16', 'CVB', 'i18', 'i19', 'DB'],
    ('ICT', 'GB'): ['ICT', 'i8', 'i9', 'i7', 'i6', 'GB'],
    ('ICT', 'GH'): ['ICT', 'i16', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'GH'],
    ('ICT', 'VB'): ['ICT', 'i16', 'i15', 'i14', 'VBA', 'VB'],
    ('ICT', 'VBA'): ['ICT', 'i16', 'i15', 'i14', 'VBA'],
    ('ICT', 'CVB'): ['ICT', 'i16', 'CVB'],
    ('ICT', 'AB'): ['ICT', 'i8', 'i9', 'IEB', 'PB', 'i10', 'CRL', 'AB'],
    ('ICT', 'PB'): ['ICT', 'i8', 'i9', 'IEB', 'PB'],
    ('ICT', 'IEB'): ['ICT', 'i8', 'i9', 'IEB'],
    ('ICT', 'DDS'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('ICT', 'CRL'): ['ICT', 'i8', 'i9', 'IEB', 'PB', 'i10', 'CRL'],
    ('ICT', 'MTP'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'GTC', 'i20', 'MTP'],
    ('ICT', 'BG'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('ICT', 'FG'): ['ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('AB', 'NTR'): ['AB', 'i11', 'i12', 'BG', 'NTR'],
    ('AB', 'VDC'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC'],
    ('AB', 'RBS'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'RBS'],
    ('AB', 'VS'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS'],
    ('AB', 'TC'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('AB', 'IS'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('AB', 'GSL'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('AB', 'OA'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA'],
    ('AB', 'CG'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('AB', 'SS'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('AB', 'GSB'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB'],
    ('AB', 'KRC'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC'],
    ('AB', 'CP'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP'],
    ('AB', 'CS'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS'],
    ('AB', 'GTC'): ['AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC'],
    ('AB', 'CB'): ['AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'GP', 'CB'],
    ('AB', 'GP'): ['AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'GP'],
    ('AB', 'DB'): ['AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'CVB', 'i18', 'i19', 'DB'],
    ('AB', 'GB'): ['AB', 'CRL', 'i10', 'PB', 'IEB', 'i9', 'i7', 'i6', 'GB'],
    ('AB', 'GH'): ['AB', 'i11', 'GH'],
    ('AB', 'VB'): ['AB', 'i11', 'i12', 'VB'],
    ('AB', 'VBA'): ['AB', 'i11', 'i12', 'VB', 'VBA'],
    ('AB', 'CVB'): ['AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'CVB'],
    ('AB', 'ICT'): ['AB', 'CRL', 'i10', 'PB', 'IEB', 'i9', 'i8', 'ICT'],
    ('AB', 'PB'): ['AB', 'CRL', 'i10', 'PB'],
    ('AB', 'IEB'): ['AB', 'CRL', 'i10', 'PB', 'IEB'],
    ('AB', 'DDS'): ['AB', 'i11', 'i12', 'BG', 'i13', 'DDS'],
    ('AB', 'CRL'): ['AB', 'CRL'],
    ('AB', 'MTP'): ['AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC', 'i20', 'MTP'],
    ('AB', 'BG'): ['AB', 'i11', 'i12', 'BG'],
    ('AB', 'FG'): ['AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('PB', 'NTR'): ['PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'BG', 'NTR'],
    ('PB', 'VDC'): ['PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC'],
    ('PB', 'RBS'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('PB', 'VS'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'VS'],
    ('PB', 'TC'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC'],
    ('PB', 'IS'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('PB', 'GSL'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('PB', 'OA'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('PB', 'CG'): ['PB', 'IEB', 'i9', 'i7', 'i18', 'i19', 'i20', 'MTP', 'i4', 'CG'],
    ('PB', 'SS'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('PB', 'GSB'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB'],
    ('PB', 'KRC'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC'],
    ('PB', 'CP'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'CP'],
    ('PB', 'CS'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS'],
    ('PB', 'GTC'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'GTC'],
    ('PB', 'CB'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB'],
    ('PB', 'GP'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'GP'],
    ('PB', 'DB'): ['PB', 'IEB', 'i9', 'i7', 'i18', 'i19', 'DB'],
    ('PB', 'GB'): ['PB', 'IEB', 'i9', 'i7', 'i6', 'GB'],
    ('PB', 'GH'): ['PB', 'i10', 'CRL', 'AB', 'i11', 'GH'],
    ('PB', 'VB'): ['PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'VB'],
    ('PB', 'VBA'): ['PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'VB', 'VBA'],
    ('PB', 'CVB'): ['PB', 'IEB', 'i9', 'i8', 'ICT', 'i16', 'CVB'],
    ('PB', 'ICT'): ['PB', 'IEB', 'i9', 'i8', 'ICT'],
    ('PB', 'AB'): ['PB', 'i10', 'CRL', 'AB'],
    ('PB', 'IEB'): ['PB', 'IEB'],
    ('PB', 'DDS'): ['PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'BG', 'i13', 'DDS'],
    ('PB', 'CRL'): ['PB', 'i10', 'CRL'],
    ('PB', 'MTP'): ['PB', 'IEB', 'i9', 'i7', 'i18', 'i19', 'i20', 'MTP'],
    ('PB', 'BG'): ['PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'BG'],
    ('PB', 'FG'): ['PB', 'IEB', 'i9', 'i7', 'i18', 'i19', 'i20', 'MTP', 'i4', 'FG'],
    ('IEB', 'NTR'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('IEB', 'VDC'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'VDC'],
    ('IEB', 'RBS'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'RBS'],
    ('IEB', 'VS'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC', 'i2', 'i25', 'i26', 'VS'],
    ('IEB', 'TC'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC'],
    ('IEB', 'IS'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS'],
    ('IEB', 'GSL'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('IEB', 'OA'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA'],
    ('IEB', 'CG'): ['IEB', 'i9', 'i7', 'i18', 'i19', 'i20', 'MTP', 'i4', 'CG'],
    ('IEB', 'SS'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB', 'i24', 'OA', 'GSL', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('IEB', 'GSB'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'GSB'],
    ('IEB', 'KRC'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'KRC'],
    ('IEB', 'CP'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'CP'],
    ('IEB', 'CS'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'i3', 'CP', 'CS'],
    ('IEB', 'GTC'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB', 'i22', 'i21', 'GTC'],
    ('IEB', 'CB'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP', 'CB'],
    ('IEB', 'GP'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'GP'],
    ('IEB', 'DB'): ['IEB', 'i9', 'i7', 'i18', 'i19', 'DB'],
    ('IEB', 'GB'): ['IEB', 'i9', 'i7', 'i6', 'GB'],
    ('IEB', 'GH'): ['IEB', 'PB', 'i10', 'CRL', 'AB', 'i11', 'GH'],
    ('IEB', 'VB'): ['IEB', 'PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'VB'],
    ('IEB', 'VBA'): ['IEB', 'i9', 'i8', 'i17', 'i14', 'VBA'],
    ('IEB', 'CVB'): ['IEB', 'i9', 'i8', 'ICT', 'i16', 'CVB'],
    ('IEB', 'ICT'): ['IEB', 'i9', 'i8', 'ICT'],
    ('IEB', 'AB'): ['IEB', 'PB', 'i10', 'CRL', 'AB'],
    ('IEB', 'PB'): ['IEB', 'PB'],
    ('IEB', 'DDS'): ['IEB', 'PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'BG', 'i13', 'DDS'],
    ('IEB', 'CRL'): ['IEB', 'PB', 'i10', 'CRL'],
    ('IEB', 'MTP'): ['IEB', 'i9', 'i7', 'i18', 'i19', 'i20', 'MTP'],
    ('IEB', 'BG'): ['IEB', 'PB', 'i10', 'CRL', 'AB', 'i11', 'i12', 'BG'],
    ('IEB', 'FG'): ['IEB', 'i9', 'i7', 'i18', 'i19', 'i20', 'MTP', 'i4', 'FG'],
    ('DDS', 'NTR'): ['DDS', 'i13', 'BG', 'NTR'],
    ('DDS', 'VDC'): ['DDS', 'i13', 'BG', 'NTR', 'VDC'],
    ('DDS', 'RBS'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'RBS'],
    ('DDS', 'VS'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS'],
    ('DDS', 'TC'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('DDS', 'IS'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('DDS', 'GSL'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('DDS', 'OA'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA'],
    ('DDS', 'CG'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('DDS', 'SS'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('DDS', 'GSB'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB'],
    ('DDS', 'KRC'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC'],
    ('DDS', 'CP'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP'],
    ('DDS', 'CS'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS'],
    ('DDS', 'GTC'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'GTC'],
    ('DDS', 'CB'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB'],
    ('DDS', 'GP'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('DDS', 'DB'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('DDS', 'GB'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('DDS', 'GH'): ['DDS', 'i13', 'BG', 'i12', 'i11', 'GH'],
    ('DDS', 'VB'): ['DDS', 'i13', 'BG', 'i12', 'VB'],
    ('DDS', 'VBA'): ['DDS', 'i13', 'BG', 'i12', 'VB', 'VBA'],
    ('DDS', 'CVB'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('DDS', 'ICT'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('DDS', 'AB'): ['DDS', 'i13', 'BG', 'i12', 'i11', 'AB'],
    ('DDS', 'PB'): ['DDS', 'i13', 'BG', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB'],
    ('DDS', 'IEB'): ['DDS', 'i13', 'BG', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB', 'IEB'],
    ('DDS', 'CRL'): ['DDS', 'i13', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('DDS', 'MTP'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'MTP'],
    ('DDS', 'BG'): ['DDS', 'i13', 'BG'],
    ('DDS', 'FG'): ['DDS', 'i13', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('CRL', 'NTR'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR'],
    ('CRL', 'VDC'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC'],
    ('CRL', 'RBS'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'RBS'],
    ('CRL', 'VS'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS'],
    ('CRL', 'TC'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('CRL', 'IS'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('CRL', 'GSL'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('CRL', 'OA'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA'],
    ('CRL', 'CG'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('CRL', 'SS'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('CRL', 'GSB'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB'],
    ('CRL', 'KRC'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC'],
    ('CRL', 'CP'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP'],
    ('CRL', 'CS'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS'],
    ('CRL', 'GTC'): ['CRL', 'AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i23', 'i22', 'i21', 'GTC'],
    ('CRL', 'CB'): ['CRL', 'AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'GP', 'CB'],
    ('CRL', 'GP'): ['CRL', 'AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'GP'],
    ('CRL', 'DB'): ['CRL', 'i10', 'PB', 'IEB', 'i9', 'i7', 'i18', 'i19', 'DB'],
    ('CRL', 'GB'): ['CRL', 'i10', 'PB', 'IEB', 'i9', 'i7', 'i6', 'GB'],
    ('CRL', 'GH'): ['CRL', 'AB', 'i11', 'GH'],
    ('CRL', 'VB'): ['CRL', 'AB', 'i11', 'i12', 'VB'],
    ('CRL', 'VBA'): ['CRL', 'AB', 'i11', 'i12', 'VB', 'VBA'],
    ('CRL', 'CVB'): ['CRL', 'AB', 'i11', 'i12', 'VB', 'VBA', 'i14', 'i15', 'i16', 'CVB'],
    ('CRL', 'ICT'): ['CRL', 'i10', 'PB', 'IEB', 'i9', 'i8', 'ICT'],
    ('CRL', 'AB'): ['CRL', 'AB'],
    ('CRL', 'PB'): ['CRL', 'i10', 'PB'],
    ('CRL', 'IEB'): ['CRL', 'i10', 'PB', 'IEB'],
    ('CRL', 'DDS'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'i13', 'DDS'],
    ('CRL', 'MTP'): ['CRL', 'i10', 'PB', 'IEB', 'i9', 'i7', 'i18', 'i19', 'i20', 'MTP'],
    ('CRL', 'BG'): ['CRL', 'AB', 'i11', 'i12', 'BG'],
    ('CRL', 'FG'): ['CRL', 'AB', 'i11', 'i12', 'BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('MTP', 'NTR'): ['MTP', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('MTP', 'VDC'): ['MTP', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC'],
    ('MTP', 'RBS'): ['MTP', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS', 'i26', 'RBS'],
    ('MTP', 'VS'): ['MTP', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS'],
    ('MTP', 'TC'): ['MTP', 'i4', 'CG', 'i27', 'TC'],
    ('MTP', 'IS'): ['MTP', 'i4', 'CG', 'i27', 'TC', 'IS'],
    ('MTP', 'GSL'): ['MTP', 'i4', 'CS', 'CP', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('MTP', 'OA'): ['MTP', 'i4', 'CS', 'CP', 'i3', 'GSB', 'i24', 'OA'],
    ('MTP', 'CG'): ['MTP', 'i4', 'CG'],
    ('MTP', 'SS'): ['MTP', 'i4', 'CG', 'i27', 'i28', 'SS'],
    ('MTP', 'GSB'): ['MTP', 'i4', 'CS', 'CP', 'i3', 'GSB'],
    ('MTP', 'KRC'): ['MTP', 'i4', 'CS', 'CP', 'i3', 'KRC'],
    ('MTP', 'CP'): ['MTP', 'i4', 'CS', 'CP'],
    ('MTP', 'CS'): ['MTP', 'i4', 'CS'],
    ('MTP', 'GTC'): ['MTP', 'i20', 'GTC'],
    ('MTP', 'CB'): ['MTP', 'i20', 'GTC', 'i21', 'i22', 'CB'],
    ('MTP', 'GP'): ['MTP', 'i20', 'GTC', 'i21', 'i22', 'CB', 'GP'],
    ('MTP', 'DB'): ['MTP', 'i20', 'i19', 'DB'],
    ('MTP', 'GB'): ['MTP', 'i4', 'FG', 'GB'],
    ('MTP', 'GH'): ['MTP', 'i20', 'GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'GH'],
    ('MTP', 'VB'): ['MTP', 'i20', 'GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('MTP', 'VBA'): ['MTP', 'i20', 'GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('MTP', 'CVB'): ['MTP', 'i20', 'i19', 'i18', 'CVB'],
    ('MTP', 'ICT'): ['MTP', 'i20', 'GTC', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('MTP', 'AB'): ['MTP', 'i20', 'GTC', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB', 'i12', 'i11', 'AB'],
    ('MTP', 'PB'): ['MTP', 'i20', 'i19', 'i18', 'i7', 'i9', 'IEB', 'PB'],
    ('MTP', 'IEB'): ['MTP', 'i20', 'i19', 'i18', 'i7', 'i9', 'IEB'],
    ('MTP', 'DDS'): ['MTP', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('MTP', 'CRL'): ['MTP', 'i20', 'i19', 'i18', 'i7', 'i9', 'IEB', 'PB', 'i10', 'CRL'],
    ('MTP', 'BG'): ['MTP', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
    ('MTP', 'FG'): ['MTP', 'i4', 'FG'],
    ('BG', 'NTR'): ['BG', 'NTR'],
    ('BG', 'VDC'): ['BG', 'NTR', 'VDC'],
    ('BG', 'RBS'): ['BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'RBS'],
    ('BG', 'VS'): ['BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS'],
    ('BG', 'TC'): ['BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC'],
    ('BG', 'IS'): ['BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS'],
    ('BG', 'GSL'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('BG', 'OA'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB', 'i24', 'OA'],
    ('BG', 'CG'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'CG'],
    ('BG', 'SS'): ['BG', 'NTR', 'VDC', 'i2', 'i25', 'i26', 'VS', 'IS', 'TC', 'i27', 'i28', 'SS'],
    ('BG', 'GSB'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'GSB'],
    ('BG', 'KRC'): ['BG', 'NTR', 'VDC', 'i2', 'KRC'],
    ('BG', 'CP'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP'],
    ('BG', 'CS'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS'],
    ('BG', 'GTC'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'GTC'],
    ('BG', 'CB'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB'],
    ('BG', 'GP'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('BG', 'DB'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'GTC', 'i20', 'i19', 'DB'],
    ('BG', 'GB'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG', 'GB'],
    ('BG', 'GH'): ['BG', 'i12', 'i11', 'GH'],
    ('BG', 'VB'): ['BG', 'i12', 'VB'],
    ('BG', 'VBA'): ['BG', 'i12', 'VB', 'VBA'],
    ('BG', 'CVB'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'CVB'],
    ('BG', 'ICT'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('BG', 'AB'): ['BG', 'i12', 'i11', 'AB'],
    ('BG', 'PB'): ['BG', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB'],
    ('BG', 'IEB'): ['BG', 'i12', 'i11', 'AB', 'CRL', 'i10', 'PB', 'IEB'],
    ('BG', 'DDS'): ['BG', 'i13', 'DDS'],
    ('BG', 'CRL'): ['BG', 'i12', 'i11', 'AB', 'CRL'],
    ('BG', 'MTP'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'MTP'],
    ('BG', 'FG'): ['BG', 'NTR', 'VDC', 'i2', 'KRC', 'i3', 'CP', 'CS', 'i4', 'FG'],
    ('FG', 'NTR'): ['FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR'],
    ('FG', 'VDC'): ['FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC'],
    ('FG', 'RBS'): ['FG', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS', 'i26', 'RBS'],
    ('FG', 'VS'): ['FG', 'i4', 'CG', 'i27', 'TC', 'IS', 'VS'],
    ('FG', 'TC'): ['FG', 'i4', 'CG', 'i27', 'TC'],
    ('FG', 'IS'): ['FG', 'i4', 'CG', 'i27', 'TC', 'IS'],
    ('FG', 'GSL'): ['FG', 'i4', 'CS', 'CP', 'i3', 'GSB', 'i24', 'OA', 'GSL'],
    ('FG', 'OA'): ['FG', 'i4', 'CS', 'CP', 'i3', 'GSB', 'i24', 'OA'],
    ('FG', 'CG'): ['FG', 'i4', 'CG'],
    ('FG', 'SS'): ['FG', 'i32', 'i31', 'SS'],
    ('FG', 'GSB'): ['FG', 'i4', 'CS', 'CP', 'i3', 'GSB'],
    ('FG', 'KRC'): ['FG', 'i4', 'CS', 'CP', 'i3', 'KRC'],
    ('FG', 'CP'): ['FG', 'i4', 'CS', 'CP'],
    ('FG', 'CS'): ['FG', 'i4', 'CS'],
    ('FG', 'GTC'): ['FG', 'i4', 'MTP', 'i20', 'GTC'],
    ('FG', 'CB'): ['FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'CB'],
    ('FG', 'GP'): ['FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP'],
    ('FG', 'DB'): ['FG', 'i4', 'MTP', 'i20', 'i19', 'DB'],
    ('FG', 'GB'): ['FG', 'GB'],
    ('FG', 'GH'): ['FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'GH'],
    ('FG', 'VB'): ['FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA', 'VB'],
    ('FG', 'VBA'): ['FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'i23', 'i15', 'i14', 'VBA'],
    ('FG', 'CVB'): ['FG', 'i4', 'MTP', 'i20', 'i19', 'i18', 'CVB'],
    ('FG', 'ICT'): ['FG', 'i4', 'CS', 'CP', 'i3', 'i21', 'i22', 'CB', 'GP', 'i16', 'ICT'],
    ('FG', 'AB'): ['FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB'],
    ('FG', 'PB'): ['FG', 'i4', 'MTP', 'i20', 'i19', 'i18', 'i7', 'i9', 'IEB', 'PB'],
    ('FG', 'IEB'): ['FG', 'i4', 'MTP', 'i20', 'i19', 'i18', 'i7', 'i9', 'IEB'],
    ('FG', 'DDS'): ['FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i13', 'DDS'],
    ('FG', 'CRL'): ['FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG', 'i12', 'i11', 'AB', 'CRL'],
    ('FG', 'MTP'): ['FG', 'i4', 'MTP'],
    ('FG', 'BG'): ['FG', 'i4', 'CS', 'CP', 'i3', 'KRC', 'i2', 'VDC', 'NTR', 'BG'],
}
